name: .NET Core

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: netcoreapp3.1
        # A file, directory or wildcard pattern that describes what to upload
        path: ./AnimalAdoption.Web.Portal/obj/Release/*
        # The desired behavior if no files are found using the provided path
    - name: Test
      run: dotnet test ${{ github.workspace }}/AnimalAdoption.Web.Portal.UnitTests/Web.Portal.UnitTests.csproj --no-restore --verbosity normal   
